## YAML Template.
---
spring:
  cloud:
    config:
      uri: http://localhost:8888
    stream:
      default-binder: kafka
      kafka.binder:
        brokers: localhost
        defaultBrokerPort: 9093
  kafka:
    host: localhost
    port: 9093
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          jwk-set-uri: http://localhost:9000/oauth2/jwks

  devtools:
    restart.enabled: false

management:
  endpoint.health.show-details: "ALWAYS"
  endpoints.web.exposure.include: "*"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.boot.actuate: INFO
    org.springframework.boot.actuate.endpoint: INFO
    org.springframework.boot.actuate.metrics: INFO
    org.springframework.cloud.config: INFO
    org.springframework.cloud.config.client: INFO
    org.springframework.cloud.config.server: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.client.discovery: INFO
    org.springframework.cloud.netflix.eureka: INFO
    org.springframework.security: INFO
    com.netflix.discovery: INFO
    com.netflix.eureka: INFO    
    org.springframework.web: INFO
    org.springframework.web.servlet: INFO
    org.springframework.web.client: INFO
    org.apache.kafka: INFO
    
---
spring:
  config:
    activate.on-profile: docker
  cloud:
    config:
      uri: http://config:8080
    stream:
      kafka.binder:
        brokers: kafka
        defaultBrokerPort: 9092

eureka:
  client:
    serviceUrl.defaultZone: http://discovery:8080/eureka/
