## YAML Template.
---
spring:
  cloud:
    gateway:
      routes:
          
        - id: service_a
          uri: lb://service-a
          predicates:
            - Path=/api/v1/service-a/**
          filters:
            - RewritePath=/api/v1/service-a/(?<remaining>.*), /${remaining}
            
        - id: service_b
          uri: lb://service-b
          predicates:
            - Path=/api/v1/service-b/**
          filters:
            - RewritePath=/api/v1/service-b/(?<remaining>.*), /${remaining}
            
        - id: service-a-swagger-ui-1
          uri: lb://service-a
          predicates:
            - Path=/openapi/service-a/**
          filters:
            - RewritePath=/openapi/service-a/(?<path>.*), /$\{path}
            
        - id: service-a-swagger-ui-2
          uri: lb://service-a
          predicates:
            - Path=/v3/api-docs/**
    bus:
      id: gateway

server:
  port: 8443
  forward-headers-strategy: framework
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/edge.p12
    key-store-password: changeit
    key-alias: localhost

---
spring:
  config:
    activate.on-profile: docker

server.port: 8443
    