## YAML Template.
---
server.port: 81

spring:
  datasource:
    url: jdbc:mysql://localhost/serviceadb
    port: '3306'
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: 'true'
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: 'true'
  cloud:
    function:
      definition: consumeMessage;transformCreateMessage;transformUpdateMessage;transformDeleteMessage;
    stream:
      bindings:
        transformCreateMessage-in-0:
          destination: a2CreateRequest
          group: service-a
          content-type: application/json
        transformCreateMessage-out-0:
          destination: a2CreateResponse
          content-type: application/json
        transformUpdateMessage-in-0:
          destination: a2UpdateRequest
          group: service-a
          content-type: application/json
        transformUpdateMessage-out-0:
          destination: a2UpdateResponse
          content-type: application/json

        transformDeleteMessage-in-0:
          destination: a2DeleteRequest
          group: service-a
        transformDeleteMessage-out-0:
          destination: a2DeleteResponse

springdoc:
  packages-to-scan: rs.ac.bg.fon.mas.service_a.controller
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

---
spring:
  config:
    activate.on-profile: docker
  datasource.url: jdbc:mysql://serviceadb/serviceadb
  
server.port: 8080
