## YAML Template.
---
server.port: 82

spring:
  cloud:
    function:
      definition: consumeCreateA2Message;consumeUpdateA2Message;consumeDeleteA2Message
    stream:
      bindings:
        a2-out-0:
          destination: a2
        consumeMessage-in-0:
          destination: a2
          group: service-b

        createA2-out-0:
          destination: a2CreateRequest
          content-type: application/json
        consumeCreateA2Message-in-0:
          destination: a2CreateResponse
          #destination: a2CreateRequest
          group: service-b
          content-type: application/json

        updateA2-out-0:
          destination: a2UpdateRequest
          content-type: application/json
        consumeUpdateA2Message-in-0:
          destination: a2UpdateResponse
          group: service-b
          content-type: application/json

        deleteA2-out-0:
          destination: a2DeleteRequest
          content-type: application/json
        consumeDeleteA2Message-in-0:
          destination: a2DeleteResponse
          group: service-b

---
spring:
  config:
    activate.on-profile: docker

server.port: 8080
